import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-50 dark:bg-black`}> 
        <header className="w-full bg-white dark:bg-zinc-900 shadow-sm">
          <nav className="container mx-auto flex items-center justify-between py-4 px-6">
            <a href="/" className="text-2xl font-bold tracking-tight text-blue-700 dark:text-blue-300">INTenX</a>
            <ul className="flex gap-8 text-lg font-medium">
              <li><a href="/" className="hover:text-blue-500">Home</a></li>
              <li><a href="/services" className="hover:text-blue-500">Services</a></li>
              <li><a href="/about" className="hover:text-blue-500">About</a></li>
              <li><a href="/contact" className="hover:text-blue-500">Contact</a></li>
            </ul>
          </nav>
        </header>
        <main className="container mx-auto px-4 py-8 min-h-[70vh]">{children}</main>
        <footer className="w-full bg-zinc-100 dark:bg-zinc-800 py-6 mt-12">
          <div className="container mx-auto flex flex-col md:flex-row items-center justify-between px-4">
            <div className="text-sm text-zinc-700 dark:text-zinc-300 mb-2 md:mb-0">
              <strong>INTenX Engineering Services</strong><br />
              202 Lindenwood Dr.<br />
              Michigan City, IN 46360<br />
              United States<br />
              <span>Email: <a href="mailto:info@intenx.io" className="underline">info@intenx.io</a></span>
            </div>
            <div className="text-xs text-zinc-500 dark:text-zinc-400">
              Site created using Next.js<br />
              &copy; {new Date().getFullYear()} INTenX
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
